# Generated by Django 3.1.7 on 2021-04-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0003_catfact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatFact',
        ),
    ]
